artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/dipan97-hue/dataset/raw/refs/heads/main/archive.zip 
  local_data_files : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


data validation:
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/WineQT.csv
  status_file : artifacts/data_validation/status.txt

