artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/dipan97-hue/dataset/raw/refs/heads/main/archive.zip 
  local_data_files : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


data validation:
  root_dir : artifacts/data_validation
  unzip_data_dir : artifacts/data_ingestion/WineQT.csv
  status_file : artifacts/data_validation/status.txt

data transformation:
  root_dir : artifacts/data_transformation
  data_path : artifacts/data_ingestion/WineQT.csv
  
model_trainer:
  root_dir : artifacts/model_trainer
  train_path : artifacts/data_transformation/train.csv
  test_path : artifacts/data_transformation/test.csv
  model_name : model.joblib

model evaluation:
  root_dir : artifacts/model_evaluation
  model_path : artifacts/model_trainer/model.joblib
  test_path : artifacts/data_transformation/test.csv
  metrics_path : artifacts/model_evaluation/metrics.json

